name: Clippy
on: [push, pull_request]
jobs:
  clippy:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: --all-targets --locked -- -D warnings
          name: Clippy Output
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: --all-targets --locked --all-features -- -D warnings
          name: Clippy (All features) Output
